import { test, expect } from "../fixtures/test-base";

/**
 * [check:10] create-dashboard
 *
 * Drives the real "Add Dashboard" UI flow: click the sidebar nav button
 * (DashboardLinks.tsx), which opens a brand-new (unsaved) dashboard with an
 * app-generated unique name ("My Dashboard", "My Dashboard(1)", …), then click
 * Save (which POSTs /dashboard). The name is chosen by the app, so we read it
 * back off the page rather than picking one.
 *
 * Backend assert: api.dashboards.getDashboards() contains the new dashboard name.
 * UI assert: the dashboard page renders with that name and it appears as a
 * sidebar nav link.
 */
test.describe("[check:10] create-dashboard", () => {
  test("creating a dashboard persists it and renders the page", async ({
    dashboard,
    api,
  }) => {
    // --- UI: drive the real "Add Dashboard" create flow ------------------
    // Clicking the sidebar Add button opens a new (unsaved) dashboard whose
    // unique name is generated by the app; capture it for the assertions.
    const dashboardName = await dashboard.addViaNav();
    expect(dashboardName).not.toBe("");

    await expect(dashboard.root).toBeVisible();
    await expect(dashboard.name).toHaveText(dashboardName);

    // Save persists the (empty-layout) dashboard via POST /dashboard. The save
    // handler depends on the page's data layer being ready, which can lag the
    // first render in dev — so re-click Save until the dashboard is persisted
    // (backend assert) rather than clicking once and hoping.
    await expect(dashboard.saveButton).toBeVisible();
    await expect(async () => {
      await dashboard.saveButton.click();
      const names = (await api.dashboards.getDashboards()).map((d: any) => d.dashboard_name);
      expect(names).toContain(dashboardName);
    }).toPass({ timeout: 30_000, intervals: [1_500, 3_000, 5_000] });

    // --- UI assert: the dashboard renders and is navigable ----------------
    await expect(dashboard.name).toHaveText(dashboardName);

    // Sidebar link for the saved dashboard (DashboardLink renders the name).
    await expect(dashboard.navLink(dashboardName).first()).toBeVisible();
  });
});
